name: 'Build Directory'

description: 'Standard build process for the current directory'

inputs:

  build_tag:
    description: Tag the build is based on (information only)
    required: true
    default: ""

  build_directory:
    description: Directory with the checked out sources
    required: false
    default: .

  build_version:
    description: Version number of the artifact
    required: false
    default: dry-run

  build_version_override:
    description: Override of the build version
    required: false
    default: ""

  build_type:
    description: Type of the build. 'tag' or 'dry-run'
    required: true
    default: "dry-run"

outputs:

  distribution:
    description: Distribution file
    value: ${{ steps.set-output.outputs.distribution }}

  build_type:
    description: Build type
    value: ${{ steps.set-output.outputs.build_type }}

  build_version:
    description: Build version
    value: ${{ steps.set-output.outputs.build_version }}

  build_version_override:
    description: Build version override
    value: ${{ steps.set-output.outputs.build_version_override }}

  build_tag:
    description: Build tag
    value: ${{ steps.set-output.outputs.build_tag }}

  build_ref:
    description: Build ref
    value: ${{ steps.set-output.outputs.build_ref }}

runs:

  using: "composite"

  steps:

    # Valid build tags need to match the format 'vX.Y.Z'

    - name: Setup Environment
      id: setup-environment
      shell: bash
      run: |

        echo "build_tag=${{inputs.build_tag}}" >> "$GITHUB_ENV"
        echo "build_directory=${{inputs.build_directory}}" >> "$GITHUB_ENV"
        echo "build_version=${{inputs.build_version}}" >> "$GITHUB_ENV"
        echo "build_version_override=${{inputs.build_version_override}}" >> "$GITHUB_ENV"

        build_stamp=$( date +%Y%m%d%H%M%S )
        build_ref="$( git rev-parse HEAD )"
        echo "build_stamp=$build_stamp" >> "$GITHUB_ENV"
        echo "build_ref=$build_ref" >> "$GITHUB_ENV"

    - name: Set build_tag from git
      id: Set-build-version
      if: env.build_type == 'dry-run' && env.build_stamp != ''
      shell: bash
      run: |

        set +e
        build_tag=$( git tag --merged | grep -v "^v[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -1 )
        set -e

        if [[ -z "$build_tag" ]] ; then 

          echo "No build_tag found in current branch, checking full repo."
          set +e
          build_tag=$( git tag --list 'v*' | grep -v "^v[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -1 )
          set -e

        fi

        if [[ -z "$build_tag" ]] ; then 

            build_tag="v0.0.1"
            echo "No build_tag found in repo, using '$build_tag'."

        fi

        echo "Setting build_tag to '$build_tag'."
        echo "build_tag=$build_tag" >> "$GITHUB_ENV"

    # Check and cleanup the build version

    - name: Check for valid tag
      id: check-valid-tag
      shell: bash
      run: |

        if [[ ! "$build_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then 

          echo "Invalid build_tag format: '$build_tag'. Aborting."
          exit 1

        fi

    # Check the tag and version

    - name: Check and fix version
      id: check-valid-version
      shell: bash
      run: |

        if [[ -z "$build_version" ]] ; then
        
          echo "Substituting build_version with build_tag '$build_tag'."
          build_version=$( echo "$build_tag" | sed -n "s/^v*\([0-9]*\.[0-9]*\.[0-9]*$\)/\1/p" )
          
        fi

        if [[ ! "$build_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([0-9.]+)?$ ]] ; then 

          echo "Invalid build_version format: '$build_version'. Aborting."
          exit 1

        fi

        if [[ "$build_type" == "dry-run" ]] ; then 

          echo "Extending build_version with build_stamp '$build_stamp' for 'dry-run'."
          build_version="$build_version.$build_stamp"

        fi

        echo "Found valid build version '$build_version'."
        echo "build_version=$build_version" >> "$GITHUB_ENV"

    # Setup build environment

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build dependencies
      id: install-depenencies
      shell: bash
      run: python3 -m pip install --upgrade pip setuptools wheel build virtualenv jinja2

      # Replace placeholders in the templates with the environment variables

    - name: Process templates
      id: process-templates
      shell: python
      run: |
        import sys
        import os
        import jinja2

        env = jinja2.Environment(loader = jinja2.FileSystemLoader('templates'))
        variables = { 
          'build_version': None,
          'build_version_override': None,
          'build_type': None,
          'build_ref': None,
          'build_tag': None,
        }

        for key in variables.keys():

          if key not in os.environ:

            print(f"Error: Environment variable '{key}' not found!")
            sys.exit(10)

          variables[key] = os.environ[key]

        for filename in env.list_templates():

          template = env.get_template(filename)
          output = template.render(variables)

          with open(filename, 'w') as f:

            f.write(output)

    # Do the actual build

    - name: Build
      id: build
      shell: bash
      run: |
        python -m build --sdist .

    # Check the name of the artifact we build

    - name: Determine distribution
      id: determine-distribution
      shell: bash
      run: |
        find dist -type f -ls
        distribution=$( cd dist && ls -1 *"-$build_version.tar.gz" | head -1 )
        echo "distribution=$distribution" >> "$GITHUB_ENV"

    # Write some meta information to the artifact and set the output of the job

    - name: Create distribution meta-information
      id: create-distribution-meta-information
      shell: bash
      run: |
        mkdir dist/META
        echo "$distribution"  > dist/META/DISTRIBUTION
        echo "$build_type"    > dist/META/TYPE
        echo "$build_version" > dist/META/VERSION
        echo "$build_tag"     > dist/META/TAG
        echo "$build_ref"     > dist/META/REF

        if [[ ! -z "$build_version_override" ]]; then

          echo "$build_version_override" > dist/META/VERSION_OVERRIDE

        fi

    # Set the output for the build job

    - name: Set output
      id: set-output
      shell: bash
      run: |
        echo "distribution=$distribution"   >> "$GITHUB_OUTPUT"
        echo "build_type=$build_type" >> "$GITHUB_OUTPUT"
        echo "build_version=$build_version" >> "$GITHUB_OUTPUT"
        echo "build_version_override=$build_version_override" >> "$GITHUB_OUTPUT"
        echo "build_tag=$build_tag"         >> "$GITHUB_OUTPUT"
        echo "build_ref=$build_ref"         >> "$GITHUB_OUTPUT"

        echo "Set distribution='$distribution'."
        echo "Set build_type='$build_type'."
        echo "Set build_version='$build_version'."
        echo "Set build_version_override='$build_version_override'."
        echo "Set build_tag='$build_tag'."
        echo "Set build_ref='$build_ref'."

    - name: "Upload artifacts"
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: distribution
        if-no-files-found: error
        retention-days: 2
        path: |
          dist/${{ env.distribution }}
          dist/META
